In [1]:
import numpy as np
#numerical python - библиотека для вычислений

In [2]:
x = [2, 4, 5]
y = [10, 4, 2]
print(x + y)

[2, 4, 5, 10, 4, 2]


In [4]:
print(type(x + y))

<class 'list'>


In [5]:
x_np = np.array(x)
y_np = np.array(y)
print(x_np + y_np)

[12  8  7]


In [6]:
print(type(x_np + y_np))
#n dimensional array = n-мерный массив

<class 'numpy.ndarray'>


In [7]:
print(x_np * 2)

[ 4  8 10]


In [8]:
print(x_np ** 7)

[  128 16384 78125]


In [9]:
print(x_np > 3)
# [2, 4, 5]

[False  True  True]


In [10]:
print(x_np[x_np > 3])

[4 5]


In [11]:
z_np = np.array(['cat', 1, 2.4, True]) #хранит только гомогенные данные
# другими словами, объекты одного типа данных
print(['cat', 1, 2.4, True])
print(z_np)

['cat', 1, 2.4, True]
['cat' '1' '2.4' 'True']


In [12]:
z_np = np.array([1, 2.4, True])
print(z_np)

[1.  2.4 1. ]


In [13]:
z_np = np.array([1, True])
print(z_np)

[1 1]


In [15]:
age = np.array([18, 20, 43, 23, 14, 52, 12])

In [16]:
print(age < 18)

[False False False False  True False  True]


In [18]:
print((age < 18) | (age >= 35)) #логическое И - & (амперсанд) 

[False False  True False  True  True  True]


In [20]:
A = np.array([[2, 5, 7], [29, 5, 6]])
print(A)

[[ 2  5  7]
 [29  5  6]]


In [21]:
print(A.shape) #аттрибут shape (отличается от метода отсутствием 
# круглых скобок в конце)

(2, 3)


In [22]:
print(A.ndim) #n dimensions

2


In [ ]:
# попробовать создать 3-D матрицу

In [23]:
print(A.size) #кол-во элементов в матрице

6


In [24]:
print(A[0][1])
print(A[0, 1])

5
5


In [25]:
print(A[:, 2])

[7 6]


# Введение в Pandas

In [26]:
#pandas = pannel data
import pandas as pd

In [27]:
df = pd.DataFrame() #набор данных
df

Empty DataFrame
Columns: []
Index: []

In [28]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [30]:
df['STATS'] = [10, 8, 9]
df

STATS
0     10
1      8
2      9

In [31]:
df['PROG'] = [9, 7, 8]
df

STATS  PROG
0     10     9
1      8     7
2      9     8

In [35]:
print(df.head(2))
df

   STATS  PROG
0     10     9
1      8     7


STATS  PROG
0     10     9
1      8     7
2      9     8

In [36]:
df['PROG'].name

'PROG'

In [37]:
df['PROG'].dtype #data type

dtype('int64')

In [38]:
df['PROG'].values

array([9, 7, 8])

In [39]:
type(df['PROG'].values)

numpy.ndarray

In [40]:
df['AVERAGE'] = (df['STATS'] + df['PROG']) / 2
df #comment

STATS  PROG  AVERAGE
0     10     9      9.5
1      8     7      7.5
2      9     8      8.5

In [41]:
df.shape

(3, 3)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   STATS    3 non-null      int64  
 1   PROG     3 non-null      int64  
 2   AVERAGE  3 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 200.0 bytes


In [43]:
df.columns

Index(['STATS', 'PROG', 'AVERAGE'], dtype='object')

In [44]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [45]:
df.index += 1
df

STATS  PROG  AVERAGE
1     10     9      9.5
2      8     7      7.5
3      9     8      8.5

In [47]:
df.iloc[0] #index location ищет по порядковому значению

STATS      10.0
PROG        9.0
AVERAGE     9.5
Name: 1, dtype: float64

In [48]:
df.loc[1] #ищет кокретное название индекса

STATS      10.0
PROG        9.0
AVERAGE     9.5
Name: 1, dtype: float64

In [50]:
df.index = ['Mark', 'Alice', 'Petya']
df

STATS  PROG  AVERAGE
Mark      10     9      9.5
Alice      8     7      7.5
Petya      9     8      8.5

In [51]:
df.iloc[0]

STATS      10.0
PROG        9.0
AVERAGE     9.5
Name: Mark, dtype: float64

In [53]:
df.loc['Mark']

STATS      10.0
PROG        9.0
AVERAGE     9.5
Name: Mark, dtype: float64

In [54]:
df['STATS'][1]

8

In [55]:
df.loc['Alice', 'STATS']

8

In [56]:
pd.DataFrame({'a' : [2, 4], 'b' : [4, 6]})

a  b
0  2  4
1  4  6